In [359]:
## Python Programming Functions
x=1
y=2
x+y
z = "string"

type(z)

str

In [360]:
def add_number(x,y):
    return x+y
add_number(1,2)

3

In [363]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
# add_numbers(1,2,3)
add_numbers(1,2)

3

In [364]:
#Use type to return the object's type
type('This is a string')

str

In [365]:
type(None)

NoneType

In [366]:
type(1)

int

In [367]:
type(1.0)

float

In [368]:
type(add_numbers)

function

In [369]:
# Tuples are an immutable data structure (cannot be altered).
x = (1, 'a', 2, 'b')
type(x)

tuple

In [370]:
# Lists are a mutable data structure.
x = [1, 'a', 2, 'b']
type(x)

list

In [371]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [372]:
# This is an example of how to loop through each item in the list.
for item in x:
    print(item)

1
a
2
b
3.3


In [373]:
# Use + to concatenate lists.
[1,2] + [3,4]

[1, 2, 3, 4]

In [374]:
# Use * to repeat lists.
[1]*3

[1, 1, 1]

In [375]:
#  Use the in operator to check if something is inside a list.
1 in [1, 2, 3]

True

In [376]:
#  Now let's look at strings. Use bracket notation to slice a string.
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters

T
T
Th


In [377]:
#  This will return the last element of the string.
x[-1]

'g'

In [382]:
#  This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.
x[-4:2]

''

In [379]:
#  This is a slice from the beginning of the string and stopping before the 3rd element.
x[:3]

'Thi'

In [380]:
#  And this is a slice starting from the 3rd element of the string and going all the way to the end.
x[3:]

's is a string'

In [383]:
firstname = 'Bharat'
lastname = 'Gera'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Bhar' in firstname)

Bharat Gera
BharatBharatBharat
True


In [384]:
# Make sure you convert objects to strings before concatenating.
'Chris' + 2

TypeError: must be str, not int

In [385]:
'Chris' + str(2)

'Chris2'

In [387]:
#  split returns a list of all the words in a string, or a list split on a specific character.
firstname = 'Bharat Abheet'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Gera Gupta'.split(' ') # [-1] selects the last element of the list
print(firstname)
print(lastname)


Bharat
['Gera', 'Gupta']


In [388]:
#  Dictionaries associate keys with values.
x = {'Bharat Gera': 'bharat.gera@vfirst.com', 'Abheet Gupta': 'abheet.gupta@vfirst.com'}
x['Bharat Gera'] # Retrieve a value by using the indexing operator

'bharat.gera@vfirst.com'

In [389]:
x['sachin'] = None
x

{'Abheet Gupta': 'abheet.gupta@vfirst.com',
 'Bharat Gera': 'bharat.gera@vfirst.com',
 'sachin': None}

In [393]:
#  Iterate over all of the keys:
for name, value in x.items():
    print(name,value)

Bharat Gera bharat.gera@vfirst.com
Abheet Gupta abheet.gupta@vfirst.com
sachin None


In [391]:
 # Iterate over all of the values
for email in x.values():
    print(email)

bharat.gera@vfirst.com
abheet.gupta@vfirst.com
None


In [394]:
# Python Programming Language: Numeric Python (Numpy)
import numpy as np

In [396]:
# Create a list and convert it to a numpy array
mylist = [1, 2, 3]
type(np.array(mylist))


numpy.ndarray

In [397]:
#  Or just pass in a list directly
arr1 = np.array([1,2,3,4])

In [398]:
# Pass in a list of lists to create a multidimensional array.
arr2 = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [400]:
# Use the shape method to find the dimensions of the array. (rows, columns)
arr2.shape

(3, 3)

In [402]:
#  arange returns evenly spaced values within a given interval
arr3 = np.arange(0,30,2)
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [404]:
arr3.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [406]:
# linspace returns evenly spaced numbers over a specified interval.
lin = np.linspace(1,3,9)
lin

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [408]:
# resize changes the shape and size of array in-place.
lin.resize(3,3)
lin

array([[ 1.  ,  1.25,  1.5 ],
       [ 1.75,  2.  ,  2.25],
       [ 2.5 ,  2.75,  3.  ]])

In [409]:
#  ones returns a new array of given shape and type, filled with ones.
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [410]:
#  zeros returns a new array of given shape and type, filled with zeros.
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [411]:
#  eye returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [412]:
#  Create an array using repeating list (or see np.tile)
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [414]:
#  Repeat elements of an array using repeat.
np.repeat([1,2,3],2)

array([1, 1, 2, 2, 3, 3])

In [415]:
# Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print(x-y)

[5 7 9]
[-3 -3 -3]


In [416]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [417]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


In [418]:
# Dot Product
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [419]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


In [420]:
# The shape of array z is (2,3) before transposing.
z.shape

(2, 3)

In [421]:
# Transposing
#  The number of rows has swapped with the number of columns.
z.T
z.T.shape

(3, 2)

In [423]:
# Use .dtype to see the data type of the elements in the array.
z = np.array([1,'123'])
z.dtype

dtype('<U21')

In [425]:
#  Use .astype to cast to a specific type.
z = z.astype('f')
z.dtype

dtype('float32')

In [426]:
# Numpy has many built in math functions that can be performed on arrays.
a = np.array([-4, -2, 1, 3, 5])

In [428]:
a.sum()

3

In [429]:
a.max()

5

In [430]:
a.min()

-4

In [431]:
a.mean()

0.59999999999999998

In [432]:
a.std()

3.2619012860600183

In [433]:
#  argmax and argmin return the index of the maximum and minimum values in the array.
a.argmax()

4

In [434]:
a.argmin()

0

In [438]:
# Indexing / Slicing
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [439]:
#  Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.
s[0],s[2],s[-1]

(0, 4, 144)

In [440]:
# Use : to indicate a range. array[start:stop]
# Leaving start or stop empty will default to the beginning/end of the array.
s[1:5]

array([ 1,  4,  9, 16])

In [441]:
# Use negatives to count from the back.
s[-4:]

array([ 81, 100, 121, 144])

In [442]:
# A second : can be used to indicate step-size. array[start:stop:stepsize]

# Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.
s[-5::2]

array([ 64, 100, 144])

In [443]:
#  Let's look at a multidimensional array.
r = np.arange(36)
print(r)
r.resize((6, 6))
r

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [444]:
# Use bracket notation to slice: array[row, column]
r[2,3]

15

In [445]:
# And use : to select a range of rows or columns
r[2,3:6]

array([15, 16, 17])

In [446]:
 #Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) 
 #the last column.
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [447]:
# This is a slice of the last row, and only every other element.
r[5,::2]

array([30, 32, 34])

In [448]:
# We can also perform conditional indexing. Here we are selecting values from the array 
# that are greater than 30. (Also see np.where)
r[r>30]

array([31, 32, 33, 34, 35])

In [206]:
#  Here we are assigning all values in the array that are greater than 30 to the value of 30.
r[r>30] = 30

In [208]:
# Copying Data
# Be careful with copying and modifying arrays in NumPy!
# r2 is a slice of r
r2 = r[::2]
r2

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [209]:
# Set this slice's values to zero ([:] selects the entire array)
r2[:]=0
# r has also been changed!

In [212]:
r2 = r.copy()

In [216]:
r2[:]=10
print(r2,'\n')
print(r)

In [218]:
# Iterating Over Arrays
# Let's create a new 4 by 3 array of random numbers 0-9.
test = np.random.randint(0,9,(4,3))

In [222]:
# Iterate by row:
for row in test:
    print(row)

In [224]:
# Iterate by index:
for i in range(len(test)):
    print (test[i])

In [228]:
#  Iterate by row and index:
for i,row in enumerate(test):
    print("row num is "+str(i)+' and value ',row)

In [229]:
#  Use zip to iterate over multiple iterables.
test2 = test**2

In [238]:
for t1,t2 in zip(test,test2):
    print(t1,'+',t2,'=',t1+t2)

In [239]:
# The Series Data Structure
import pandas as pd
pd.Series?

In [246]:
animals = ['Tiger','Lion','elephant']
pd.Series(animals)

In [245]:
numbers = [1, 2, 3]
pd.Series(numbers)

In [244]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

In [248]:
s.index

In [250]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

In [252]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

In [280]:
#Querying a Series
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

In [351]:
s.iloc[3]

In [352]:
s.loc['Sumo']

In [353]:
s[3]

In [354]:
s['Golf']

In [261]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)



In [265]:
s[0] #This won't call s.iloc[0] as one might expect, it generates an error instead

In [350]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

In [271]:
total=0
for item in s:
    total+=item
total
# OR
total = np.sum(s)
print(total)

In [349]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

In [347]:
len(s)

In [348]:
s+=2 #adds two to each item in s using broadcasting
s.head()

In [291]:
#The DataFrame Data Structure
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

In [ ]:
df.loc['Store 2']

In [ ]:
df.loc['Store 1']

In [294]:
df.loc['Store 1']['Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [345]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1',axis=0)
copy_df

In [344]:
#Dataframe Indexing and Loading
olmp = pd.read_csv('/home/bharat/olympics.csv')
olmp

In [343]:
olmp = pd.read_csv('/home/bharat/olympics.csv',index_col=0,skiprows=1)
olmp

In [342]:
olmp.columns

In [341]:
for col in olmp.columns:
    if col[:2] == '01':
        olmp.rename(columns={col:'Gold'+col[4:]},inplace=True)
    if col[:2] == '02':
        olmp.rename(columns={col:'SILVER'+col[4:]},inplace=True)
    if col[:2] == '03':
        olmp.rename(columns={col:'BRONZE'+col[4:]},inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' + col[1:]}, inplace=True)
olmp.head()

In [326]:
olmp['Gold']>0

In [338]:
# only gold
only_gold=olmp.where(olmp['Gold']>0)
only_gold.head()

In [339]:
olmp['Gold'].count()

In [340]:
only_gold = only_gold.dropna()
only_gold.head()